# Turn a set of switches on / off at a given time determined by a time helper entity

- id: '1652259160062'
  alias: 'MT LED: 1.5 x 3m Lights On'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_1_on #you need to make this helper
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.timer_1_on_switch  #you need to make this helper
      state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.v3_room_fan
      - switch.tent2
      - switch.s4_outside_house_lights
      - switch.v2_blurple_led
      - switch.c3_dehumidifier
      - switch.a1_led
  mode: single
- id: '1652259825974'
  alias: 'MT LED: 1.5 x 3m Lights Off'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_1_off #you need to make this helper
  condition:
  - condition: state
    entity_id: input_boolean.timer_1_off_switch #you need to make this helper
    state: 'on'
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.v3_room_fan
      - switch.tent2
      - switch.s4_outside_house_lights
      - switch.v2_blurple_led
      - switch.c3_dehumidifier
      - switch.a1_led
      
      
# Change co2 input targets for night and day based off the previous automations times

- id: '1655470596692'
  alias: 'MT Co2: Change target to 100ppm at Night'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_1_off #you need to make this helper as part of the lights on/off automation
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: 100
    target:
      entity_id: input_number.co2_target #you need to make this helper as part of the node red co2 automation
  mode: single
- id: '1655470652471'
  alias: 'MT Co2: Change target to 1400ppm at Day'
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_1_on #you need to make this helper as part of the lights on/off automation
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: 1300
    target:
      entity_id: input_number.co2_target #you need to make this helper as part of the node red co2 automation
  mode: single
  
  
  #Irrigation 
  
  - id: '1655704996496'
  alias: Water 1 Automation - On
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_3 #need to make a helper
  condition:
  - condition: state
    entity_id: input_boolean.water_1_switch #make helpers like these for each watering time to enable/disable the automation
    state: 'on'
  action:
  - type: turn_on
    device_id: ba27102ba26bc74e38f9a538aaa62a2d #you can delete these bits
    entity_id: switch.s1_water_pump #this is the switch that turns the pump on/off
    domain: switch 
  mode: single
- id: '1655705049121'
  alias: Water 1 Automation - Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_1_off #need to make a helper
  condition:
  - condition: state
    entity_id: input_boolean.water_1_switch
    state: 'on'
    enabled: false
  action:
  - type: turn_off
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump 
    domain: switch
  mode: single
- id: '1655709663672'
  alias: Water 2 Automation - Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_2_off 
  condition:
  - condition: state
    entity_id: input_boolean.water_1_switch
    state: 'on'
    enabled: false
  action:
  - type: turn_off
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709713552'
  alias: Water 2 Automation - On
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_2_on
  condition:
  - condition: state
    entity_id: input_boolean.water_2_switch
    state: 'on'
  action:
  - type: turn_on
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709760494'
  alias: Water 3 Automation - On
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_3_on
  condition:
  - condition: state
    entity_id: input_boolean.water_3_off_switch
    state: 'on'
  action:
  - type: turn_on
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709796556'
  alias: Water 3 Automation - Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_3_off
  condition:
  - condition: state
    entity_id: input_boolean.water_1_switch
    state: 'on'
    enabled: false
  action:
  - type: turn_off
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709846778'
  alias: Water 4 Automation - On
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_4_on
  condition:
  - condition: state
    entity_id: input_boolean.water_4_off_switch
    state: 'on'
  action:
  - type: turn_on
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709883433'
  alias: Water 4 Automation - Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_4_off
  condition:
  - condition: state
    entity_id: input_boolean.water_1_switch
    state: 'on'
    enabled: false
  action:
  - type: turn_off
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709918165'
  alias: Water 6 Automation - On
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_6_on
  condition:
  - condition: state
    entity_id: input_boolean.water_6_off_switch
    state: 'on'
  action:
  - type: turn_on
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709941640'
  alias: Water 5 Automation - On
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_5_on
  condition:
  - condition: state
    entity_id: input_boolean.water_5_on_switch
    state: 'on'
  action:
  - type: turn_on
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655709985545'
  alias: Water 5 Automation - Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_5_off
  condition:
  - condition: state
    entity_id: input_boolean.water_1_switch
    state: 'on'
    enabled: false
  action:
  - type: turn_off
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump
    domain: switch
  mode: single
- id: '1655710115340'
  alias: Water 6 Automation - Off
  description: ''
  trigger:
  - platform: time
    at: input_datetime.water_6_off
  condition:
  - condition: state
    entity_id: input_boolean.water_1_switch
    state: 'on'
    enabled: false
  action:
  - type: turn_off
    device_id: ba27102ba26bc74e38f9a538aaa62a2d
    entity_id: switch.s1_water_pump #this is the switch that turns the pump on/off
    domain: switch
  mode: single
  
  
  
#co2 safety backup auto off automation

- id: '1660046482999'
  alias: 'MT Co2: Turn off co2 above 2000'  #this will turn off the co2 solenoid if a co2 sensor goes above 2000ppm
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.co2_1_co2_3 #change this sensor to whatever your backup co2 sensor is i.e. outuside of your tent or grow space
    above: '2000' 
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.co2_solendoid #the name of your co2 solenoid switch
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.co2_target #this sets the co2 target to 0 so that the node red automation doesnt keep kicking it back on
  - service: light.turn_on #this turns on a bunch of lights in my house and makes them go red
    data:
      brightness: 255 
      rgb_color:
      - 238
      - 0
      - 255
    target:
      entity_id:
      - light.office_1
      - light.office_2
      - light.hue_lightstrip_plus_1
  - service: notify.mobile_app_xx_s21 #this sends a notification that is high priority ant stick to my phone to let me know there was a co2 problem (but the solenoid should have already been turned off) 
    data:
      message: CO2 Above 2000
      data:
        color: red
        sticky: true
        tag: co2-high
        channel: co2alert
        ttl: 0
        priority: high
        ledColor: red
        vibrationPattern: 100, 1000, 100, 1000, 100
  mode: single
  
  
  #auto irrigation based on moisture level 
  
  - id: '1679211699730'
  alias: 'MT: Irrigation turn on at 30%'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.plant_sensor_median_moisture #this is the median moisture helper for like 8 different moisturue sensors combined
    below: 35
  condition:
  - condition: time
    after: input_datetime.time_1_on #this means it will only run if the lights are on
    before: input_datetime.time_1_off #this means it will only run if the lights are on
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.s1_water_pump
  - delay:
      hours: 0
      minutes: 5 #this turns the irrigation off after 5 minutues (this is a test) - but for me, 5 mintues is 1L per plant
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.s1_water_pump
  mode: single

