#this will create two entities in Home Assisitant. Leaf VPD and Tent VPD which is basically environment around the leaf VPD. It doesnt have to be a tent. 

template:
  - sensor:
        - name: "Leaf VPD"
          unit_of_measurement: "kPa"
          state: >
            {% set T_Air = states('sensor.your_temp') | float %}
            {% set T_Leaf = states('sensor.your_leaf_temp') | float %}
            {% set RH = states('sensor.your_humidity') | float %}
            {% set e = 2.71828 %}
            {% set ASVP = 0.61078 * e ** (T_Air / (T_Air + 238.3) * 17.2694) %}
            {% set LSVP = 0.61078 * e ** (T_Leaf / (T_Leaf + 238.3) * 17.2694) %}
            {% set AVPD = ASVP - (ASVP * RH/100) %}
            {% set LVPD = LSVP - (ASVP * RH/100) %}
            {{ LVPD | round(2) }}
            
        - name: "Tent VPD"
          unit_of_measurement: "kPa"
          state: >
            {% set T_Air = states('sensor.your_temp') | float %}
            {% set RH = states('sensor.your_humidity') | float %}
            {% set e = 2.71828 %}
            {% set ASVP = 0.61078 * e ** (T_Air / (T_Air + 238.3) * 17.2694) %}
            {% set AVPD = ASVP * 1 - (ASVP * RH/100) %}
            {{ AVPD | round(2) }}
