#this will give you a light sensor you can adjust once you plug in the ESP32 into the potentiometer plugs of a 10v meanwell driver. 

esphome:
  name: "esp32-pwm-600w"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-93B49C"
    password: "rKfuNMJIxuMj"

captive_portal:
    
output:
  - platform: ledc
    pin: 23
    frequency: 1220 Hz
    inverted: true
    id: led600w_pwm
    channel: 10
    
light:
  - platform: monochromatic
    name: "LED 600w PWM"
    output: led600w_pwm
    gamma_correct: 1.0
