esphome:
  name: "espatom-ir-blaster-2"

esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-E9D56C"
    password: "c3qrp06B7Bj8"

captive_portal:

remote_receiver:
  pin:
    number: GPIO32
    inverted: true
  dump: all

remote_transmitter:
  pin: GPIO26
  carrier_duty_percent: 50%

climate:
  - platform: heatpumpir       # adjust to match your AC unit!
    protocol: panasonic_dke
    name: "Lounge AC"
    horizontal_default: mright
    vertical_default: up
    max_temperature: 25
    min_temperature: 16
    #sensor: sensor.ble_temperatue_c
