template:
  - sensor:
      - name: "Leaf VPD"
        unit_of_measurement: "kPa"
        state: >
          {% set T_Air = states('sensor.temperature') | float %} # Replace with your air temperature sensor
          {% set T_Leaf = states('sensor.ncir_temperature') | float %} # Replace with your leaf temperature sensor
          {% set RH = states('sensor.humidity') | float %} # Replace with your humidity sensor
          {% set e = 2.71828 %}

          # Saturation Vapor Pressure (SVP) for Air and Leaf
          {% set ASVP = 0.61078 * e ** ((17.27 * T_Air) / (T_Air + 237.3)) %}
          {% set LSVP = 0.61078 * e ** ((17.27 * T_Leaf) / (T_Leaf + 237.3)) %}

          # Actual Vapor Pressure (AVP)
          {% set AVP = ASVP * (RH / 100) %}

          # Leaf VPD Calculation
          {% set LVPD = LSVP - AVP %}
          {{ LVPD | round(2) }}

      - name: "Tent VPD"
        unit_of_measurement: "kPa"
        state: >
          {% set T_Air = states('sensor.temperature') | float %} # Replace with your air temperature sensor
          {% set RH = states('sensor.humidity') | float %} # Replace with your humidity sensor
          {% set e = 2.71828 %}

          # Saturation Vapor Pressure (SVP) for Air
          {% set ASVP = 0.61078 * e ** ((17.27 * T_Air) / (T_Air + 237.3)) %}

          # Actual Vapor Pressure (AVP)
          {% set AVP = ASVP * (RH / 100) %}

          # Tent VPD Calculation
          {% set TVPD = ASVP - AVP %}
          {{ TVPD | round(2) }}
