# ==============================================================================
# Automation: Tank Low Level Refill and Dose
# ------------------------------------------------------------------------------
# Alias and description
alias: Tank Low Level Refill and Dose
description: >-
  Manages tank refill and dosing process when water level drops below 0.6
  or manual button press. Checks pH and EC values after dosing and alerts if
  out of range.
mode: single

# ------------------------------------------------------------------------------
# Triggers: when to start this automation
trigger:
  # 1) Low‐level trigger (disabled by default)
  - platform: numeric_state
    entity_id: sensor.aqua_pro_water_level
    below: 5            # below 5% water level
    for:
      minutes: 1
    id: water_level
    enabled: false

  # 2) Manual button press
  - platform: state
    entity_id: input_button.manual_tank_fill
    id: manual_button
    enabled: true

  # 3) Binary sensor goes from “on” → “off” (tank empty)
  - platform: state
    entity_id: binary_sensor.tank_sensor_tank_level
    from: "on"
    to: "off"

  # 4) Rapid low‐level trigger at 6%
  - platform: numeric_state
    entity_id: sensor.aqua_pro_water_level
    below: 0.06

# ------------------------------------------------------------------------------
# Conditions: only run if safety switch is on and level is still low
condition:
  # Safety switch must be enabled
  - condition: state
    entity_id: input_boolean.tank_fill_safety_switch
    state: "on"

  # Water level still below threshold
  - condition: numeric_state
    entity_id: sensor.aqua_pro_water_level
    below: 0.06

# ------------------------------------------------------------------------------
# Actions: step-by-step sequence
action:
  # 1) Notify start and turn off irrigation
  - service: notify.mobile_app_s23ultra
    data:
      message: "Starting tank fill sequence - Turning off irrigation"
      data:
        tag: tank_fill_process

  # 2) Flag nutrient dosing as active
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.nutrient_dosing_active

  # 3) Shut off all irrigation relays + waste valve
  - service: switch.turn_off
    target:
      entity_id:
        - switch.f1_irrigation_relays_relay_1
        - switch.f1_irrigation_relays_relay_2
        - switch.f1_irrigation_relays_relay_3
        - switch.f1_irrigation_relays_relay_4
        - switch.waste_valve

  - delay: '00:00:05'  # wait 5 s

  # 4) Shut secondary relays
  - service: switch.turn_off
    target:
      entity_id:
        - switch.espoe_irrigation_relay_1_2
        - switch.espoe_irrigation_relay_2_4

  - delay: '00:00:05'  # wait 5 s

  # 5) Open fill valve
  - service: notify.mobile_app_s23ultra
    data:
      message: "Turning on tank fill valve"
      data:
        tag: tank_fill_process

  - service: switch.turn_on
    target:
      entity_id: switch.espoe_irrigation_relay_1_4

  - service: notify.mobile_app_s23ultra
    data:
      message: "Starting tank fill - Running for 10 minutes"
      data:
        tag: tank_fill_process

  - delay: '00:10:00'  # 10 minutes fill

  # 6) Fill complete, start circulation
  - service: notify.mobile_app_s23ultra
    data:
      title: "Tank Fill Progress"
      message: "Tank fill complete - Starting circulation"
      data:
        tag: tank_fill_process

  - service: switch.turn_off
    target:
      entity_id:
        - switch.pump_power_switch
        - switch.f1_irrigation_pump_master_switch

  - service: switch.turn_on
    target:
      entity_id:
        - switch.espoe_irrigation_relay_2_4
        - switch.espoe_irrigation_relay_1_1

  - delay: '00:00:03'  # wait 3 s

  - service: switch.turn_on
    target:
      entity_id: switch.pump_power_switch

  - delay: '00:00:02'  # wait 2 s

  - service: switch.turn_on
    target:
      entity_id: switch.f1_irrigation_pump_master_switch

  - delay: '00:00:15'  # allow pump to stabilize

  # 7) Verify pump power
  - condition: numeric_state
    entity_id: sensor.pump_power_switch_power
    above: 100

  - service: notify.mobile_app_s23ultra
    data:
      title: "Tank Fill Progress"
      message: "Starting nutrient dosing"
      data:
        tag: tank_fill_process

  # 8) If pump power drops below 100 W, reset and abort
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.pump_power_switch_power
            below: 100
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.f1_irrigation_pump_master_switch
          - delay: '00:00:05'
          - service: switch.turn_on
            target:
              entity_id: switch.f1_irrigation_pump_master_switch
          - delay: '00:00:10'
          - service: notify.mobile_app_s23ultra
            data:
              message: "URGENT: Pump power below 100W after reset. Stopping automation."
              priority: high
              data:
                tag: tank_fill_error
          - stop

  # 9) Kick off nutrient dose via MQTT
  - delay: '00:00:30'
  - service: mqtt.publish
    data:
      topic: AQU1AD04A42/ctr
      payload: >-
        {"cmd": "setNutrient", "msgid": "start_dose", "sn": "AQU1AD04A42", "monitor": 0}
  - delay: '00:03:00'
  - service: notify.mobile_app_s23ultra
    data:
      message: "Dosing complete - Starting mixing period"
      data:
        tag: tank_fill_process
  - service: mqtt.publish
    data:
      topic: AQU1AD04A42/ctr
      payload: >-
        {"cmd": "setNutrient", "msgid": "force_stop", "sn": "AQU1AD04A42", "monitor": 1}

  # 10) Shut down pumps and relays
  - service: notify.mobile_app_s23ultra
    data:
      message: "Mixing complete - Shutting down pumps"
      data:
        tag: tank_fill_process

  - service: switch.turn_off
    target:
      entity_id:
        - switch.espoe_irrigation_relay_1_4
  - delay: '00:01:00'
  - service: switch.turn_off
    target:
      entity_id:
        - switch.espoe_irrigation_relay_1_1
  - delay: '00:00:01'
  - service: switch.turn_off
    target:
      entity_id:
        - switch.espoe_irrigation_relay_2_4
  - delay: '00:05:00'

  # 11) Check pH/EC and alert if out of range
  - service: notify.mobile_app_s23ultra
    data:
      message: "Checking pH and EC levels..."
      data:
        tag: tank_fill_process

  - choose:
      # pH out of range
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: sensor.atlas_legacy_1_ph_res1
                below: 5.8
              - condition: numeric_state
                entity_id: sensor.atlas_legacy_1_ph_res1
                above: 6.2
        sequence:
          - service: notify.mobile_app_s23ultra
            data:
              title: "pH Value Out of Range"
              message: >-
                CRITICAL ALERT: pH out of range! Current pH:
                {{ states('sensor.atlas_legacy_1_ph_res1') }}. Should be between
                5.80-6.20.
              data:
                ttl: 0
                priority: high
                channel: critical_alerts
                importance: high
                vibrationPattern: [100, 1000, 100, 1000, 100]
                tag: ph_ec_alert

      # EC out of range
      - conditions:
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: sensor.atlas_legacy_1_ec_res1
                below: 2.8
              - condition: numeric_state
                entity_id: sensor.atlas_legacy_1_ec_res1
                above: 3.2
        sequence:
          - service: notify.mobile_app_s23ultra
            data:
              title: "EC Value Out of Range"
              message: >-
                CRITICAL ALERT: EC out of range! Current EC:
                {{ states('sensor.atlas_legacy_1_ec_res1') }}. Should be between
                2.80-3.20.
              data:
                ttl: 0
                priority: high
                channel: critical_alerts
                importance: high
                vibrationPattern: [100, 1000, 100, 1000, 100]
                tag: ph_ec_alert

  # 12) Final summary notification
  - service: notify.mobile_app_s23ultra
    data:
      message: >-
        Process complete - pH: {{ states('sensor.atlas_legacy_1_ph_res1') }},
        EC: {{ states('sensor.atlas_legacy_1_ec_res1') }}
      data:
        tag: tank_fill_process

  # 13) Resume irrigation scheduler if daytime, else leave it off
  - choose:
      - conditions:
          - condition: time
            after: "06:00:00"
            before: "02:00:00"
        sequence:
          - service: automation.turn_on
            target:
              entity_id: automation.f1_irrigation_irrigate_5_minutes_every_45_minutes
          - service: notify.mobile_app_s23ultra
            data:
              message: "Irrigation schedule resumed after tank fill (daytime)"
              data:
                tag: tank_fill_process
    default:
      - service: notify.mobile_app_s23ultra
        data:
          message: "Tank fill complete, but irrigation remains disabled (nighttime)"
          data:
            tag: tank_fill_process

  # 14) Cooldown and reset dosing flag
  - service: notify.mobile_app_s23ultra
    data:
      message: "Tank fill and dose sequence complete - Starting cooldown period"
      data:
        tag: tank_fill_process

  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.nutrient_dosing_active

  - delay: '01:30:00'

  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.nutrient_dosing_active
