#this is what chapt gpt has figured out so far... 
#I dont know how to configure the I2C and hx711 for the scales

# This is the bit that is erroring: 

# i2c:
#   sda: GPIO13
#   scl: GPIO15
#   scan: true

# sensor:
#   - platform: hx711
#     name: "M5Stack Scales Weight"
#     dout_pin: GPIO13  # Using SDA pin
#     clk_pin: GPIO15   # Using SCL pin

# [20:56:13][I][logger:156]: Log initialized
# [20:56:13][C][ota:483]: There have been 3 suspected unsuccessful boot attempts.
# [20:56:13][D][esp32.preferences:114]: Saving 1 preferences to flash...
# [20:56:13][D][esp32.preferences:143]: Saving 1 preferences [W][hx711:037]: HX711 is not ready for new measurements y[W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:13][D][wifi:477]: Found networks:
# [20:56:13][I][wifi:521]: - 'IoT-AP' [redacted]▂▄▆█
# [20:56:13][D][wifi:522]:     Channel: 11
# [20:56:13][D][wifi:523]:     RSSI: -55 dB
# [20:56:13][D][wifi:526]: - [redacted] [redacted]▂▄▆█
# [20:56:13][D][wifi:526]: - [redacted] [redacted]▂▄▆█
# [20:56:13][D][wifi:526]: - [redacted] [redacted]▂▄▆█
# [20:56:13][D][wifi:526]: - [redacted] [redacted]▂▄▆█
# [20:56:13][D][wifi:526]: - [redacted] [redacted]▂▄▆█
# [20:56:13][D][wifi:526]: - [redacted] [redacted]▂▄▆█[I][wifi:303]: WiFi Connecting to 'IoT-AP'...
# [20:56:13][I][wifi:597]: WiFi Connected!
# [20:56:13][C][wifi:408]:   Local MAC: C0:4E:30:12:B2:84
# [20:56:13][C][wifi:413]:   SSID: [redacted]
# [20:56:13][C][wifi:416]:   IP Address: 192.168.50.99
# [20:56:13][C][wifi:420]:   BSSID: [redacted]
# [20:56:13][C][wifi:421]:   Hostname: 'm5-dial'
# [20:56:13][C][wifi:423]:   Signal strength: -55 dB ▂▄▆█
# [20:56:13][C][wifi:427]:   Channel: 11
# [20:56:13][C][wifi:428]:   Subnet: 255.255.255.0
# [20:56:13][C][wifi:429]:   Gateway: 192.168.50.1
# [20:56:13][C][wifi:430]:   DNS1: 192.168.50.2
# [20:56:13][C][wifi:431]:   DNS2: 1.1.1.1
# [20:56:13][D][wifi:606]: Disabling AP...
# [20:56:13][C][ota:096]: Over-The-Air Updates:
# [20:56:13][C][ota:097]:   Address: m5-dial.local:3232
# [20:56:13][C][ota:103]:   OTA version: 2.
# [20:56:13][W][ota:107]: Last Boot was an unhandled reset, will proceed to safe mode in 7 restarts
# [20:56:13][C][api:025]: Setting up Home Assistant API server...
# [20:56:13][I][app:062]: setup() finished successfully!
# [20:56:13][W][component:170]: Component wifi cleared Warning flag
# [20:56:13][W][component:157]: Component api set Warning flag: unspecified
# [20:56:13][I][app:100]: ESPHome version 2024.5.5 compiled on Jun  9 2024, 20:31:20
# [20:56:13][I][app:102]: Project smarthomeyourself.m5_dial version 1.0
# [20:56:13][C][wifi:580]: WiFi:
# [20:56:13][C][wifi:408]:   Local MAC: C0:4E:30:12:B2:84
# [20:56:13][C][wifi:413]:   SSID: [redacted]
# [20:56:13][C][wifi:416]:   IP Address: 192.168.50.99
# [20:56:13][C][wifi:420]:   BSSID: [redacted]
# [20:56:13][C][wifi:421]:   Hostname: 'm5-dial'
# [20:56:13][C][wifi:423]:   Signal strength: -55 dB ▂▄▆█
# [20:56:13][C][wifi:427]:   Channel: 11
# [20:56:13][C][wifi:428]:   Subnet: 255.255.255.0
# [20:56:13][C][wifi:429]:   Gateway: 192.168.50.1
# [20:56:13][C][wifi:430]:   DNS1: 192.168.50.2
# [20:56:14][C][wifi:431]:   DNS2: 1.1.1.1
# [20:56:14][C][logger:185]: Logger:
# [20:56:14][C][logger:186]:   Level: DEBUG
# [20:56:14][C][logger:188]:   Log Baud Rate: 115200
# [20:56:14][C][logger:189]:   Hardware UART: USB_CDC
# [20:56:14][C][switch.gpio:068]: GPIO Switch 'Tare Button'
# [20:56:14][C][switch.gpio:091]:   Restore Mode: always OFF
# [20:56:14][C][switch.gpio:031]:   Pin: GPIO16
# [20:56:14][C][template.text_sensor:020]: Template Sensor 'M5Stack Scales Raw Value'
# [20:56:14][C][status:034]: Status Binary Sensor 'M5Stack Scales Status'
# [20:56:14][C][status:034]:   Device Class: 'connectivity'
# [20:56:14][C][hx711:021]: HX711 'M5Stack Scales Weight'
# [20:56:14][C][hx711:021]:   State Class: 'measurement'
# [20:56:14][C][hx711:021]:   Unit of Measurement: 'kg'
# [20:56:14][C][hx711:021]:   Accuracy Decimals: 0
# [20:56:14][C][hx711:021]:   Icon: 'mdi:scale'
# [20:56:14][C][hx711:022]:   DOUT Pin: GPIO13
# [20:56:14][C][hx711:023]:   SCK Pin: GPIO15
# [20:56:14][C][hx711:024]:   Update Interval: 1.0s
# [20:56:14][C][captive_portal:088]: Captive Portal:
# [20:56:14][C][mdns:115]: mDNS:
# [20:56:14][C][mdns:116]:   Hostname: m5-dial
# [20:56:14][C][ota:096]: Over-The-Air Updates:
# [20:56:14][C][ota:097]:   Address: m5-dial.local:3232
# [20:56:14][C][ota:103]:   OTA version: 2.
# [20:56:14][W][ota:107]: Last Boot was an unhandled reset, will proceed to safe mode in 7 restarts
# [20:56:14][C][api:139]: API Server:
# [20:56:14][C][api:140]:   Address: m5-dial.local:6053
# [20:56:14][C][api:144]:   Using noise encryption: NO
# [20:56:14][C][improv_serial:032]: Improv Serial:
# [20:56:14][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:15][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:16][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:17][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:18][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:19][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:20][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:21][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:22][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:23][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:24][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:25][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:26][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:27][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:28][W][hx711:037]: HX711 is not ready for new measurements yet!
# [20:56:29][W][hx711:037]: HX711 is not ready for new measurements yet!


substitutions:
  name: "m5-dial"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password  

esphome:
  name: ${name}
  name_add_mac_suffix: false
  project:
    name: smarthomeyourself.m5_dial
    version: "1.0"
    
  platformio_options:
    lib_deps:
      - WiFi
      - SPI
      - FS
      - Wire
      - EEPROM
      - ArduinoJson
      - m5stack/M5Unified
      - m5stack/M5Dial

external_components:
  - source:
      type: git
      url: https://github.com/SmartHome-yourself/m5-dial-for-esphome/
      ref: main
    components: [shys_m5_dial]
 
dashboard_import:
  package_import_url: github://SmartHome-yourself/m5-dial-for-esphome/shys-m5-dial.yaml@main
  import_full_config: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: DEBUG
  
api:
ota:
improv_serial:
captive_portal:

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    password: "12345678"

# Commenting out the I2C bus configuration so it will compile
# i2c:
#   sda: GPIO13
#   scl: GPIO15
#   scan: true

sensor:
  - platform: hx711
    name: "M5Stack Scales Weight"
    dout_pin: GPIO13  # Using SDA pin
    clk_pin: GPIO15   # Using SCL pin
    gain: 128
    update_interval: 1s
    id: hx711_id
    filters:
      - calibrate_linear:
          - 120 -> 0
          - 810 -> 1
      - lambda: |-
          static float tare_value = 0;
          if (id(tare).state) {
            tare_value = x;
          }
          return x - tare_value;
    unit_of_measurement: kg

binary_sensor:
  - platform: status
    name: "M5Stack Scales Status"

switch:
  - platform: gpio
    pin: GPIO16  # Use an available GPIO pin for the tare button
    id: tare
    name: "Tare Button"
    on_turn_on:
      then:
        - lambda: |-
            id(tare).publish_state(true);
        - delay: 500ms
        - lambda: |-
            id(tare).publish_state(false);

text_sensor:
  - platform: template
    name: "M5Stack Scales Raw Value"
    lambda: |-
      return to_string(id(hx711_id).state);

